# Generated by Django 4.2.1 on 2023-06-08 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Summoner',
            fields=[
                ('summonerId', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('win_rate', models.FloatField()),
                ('ranking', models.CharField(choices=[('ir', 'iron'), ('br', 'bronze'), ('sl', 'silver'), ('gl', 'gold'), ('pl', 'platinum'), ('di', 'diamond'), ('ms', 'master'), ('gm', 'grandmaster'), ('ch', 'challenger')], max_length=15)),
                ('division', models.CharField(max_length=1)),
                ('league_points', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SummonerRanking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranks.ranking')),
                ('summonerId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranks.summoner')),
            ],
        ),
    ]
